blank_issues_enabled: false
contact_links:
  - name: QQ 交流群
    url: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=_I_ZaIYwzL5bHC1CTxJgAVjkLZaWsxL0&authKey=VTCjSSwRsk43GqHa9d6s1weANUGZfYrMLZYXXAQA5QT38OUEpD%2BUogpstySwMJoz&noverify=0&group_code=244029317
    about: 问题反馈，BUG交流